Bakery/Models/Treat.cs
using System.ComponentModel.DataAnnotations;
namespace Bakery.Models;

public class Treat
{
    public int TreatId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    // public string UserId { get; set; }
    public ApplicationUser User { get; set; }
    public List<FlavorTreat> JoinEntities { get; }
}

Bakery/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Bakery.Models;

namespace Bakery.Controllers;

public class TreatsController : Controller
{
    private readonly BakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, BakeryContext db)
    {
        _userManager = userManager;
        _db = db;
    }

    public ActionResult Index()
    {
        List<Treat> model = _db.Treats.ToList();
        return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
        return View();
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<ActionResult> Create(Treat treat)
    {
        if (!ModelState.IsValid)
        {
            return View(treat);
        }
        else
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
            treat.User = currentUser;
            _db.Treats.Add(treat);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

    public ActionResult Details(int id)
    {
        Treat treat = _db.Treats
            .Include(treat => treat.JoinEntities)
            .ThenInclude(join => join.Flavor)
            .FirstOrDefault(treat => treat.TreatId == id);
        return View(treat);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
        Treat treat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
        return View(treat);
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
        _db.Treats.Update(treat);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public ActionResult Delete(int id)
    {
        Treat treat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
        _db.Treats.Remove(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddFlavor(int id)
    {
        Treat treat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
        ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Name");
        return View(treat);
    }
    [Authorize(Roles = "Admin")]
    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
#nullable enable
        FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
        if (joinEntity == null && flavorId != 0)
        {
            _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treat.TreatId, FlavorId = flavorId });
            _db.SaveChanges();
        }
        return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId, int treatId)
    {
        FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
        _db.FlavorTreats.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = treatId });
    }

}

Bakery/Views/Treats/AddFlavor.cshtml
@model Bakery.Models.Treat


<h2>Add a tag</h2>

<h4>Add a flavor to @Model.Name</h4>

@using (Html.BeginForm())
{
    <div class="form-layout">
        @Html.HiddenFor(model => model.TreatId)

        @Html.Label("Select a flavor")
        @Html.DropDownList("FlavorId")

        <input class="form-button" type="submit" value="Save" />
    </div>
}

Bakery/Views/Treats/Create.cshtml
@model Bakery.Models.Treat


<h2>Add a new treat</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
    <div class=form-layout>
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)

        @Html.LabelFor(model => model.Description)
        @Html.TextBoxFor(model => model.Description)

        <input class="form-button" type="submit" value="Add treat" />
    </div>
}

Bakery/Views/Treats/Details.cshtml
@using Bakery.Models
@model Bakery.Models.Treat

<h2>Treat Info</h2>
<hr />
<h3>@Html.DisplayFor(model => model.Name)</h3>
<h4>@Html.DisplayFor(model => model.Description)</h4>

@if (@Model.JoinEntities.Count == 0)
{
    <p>No flavors have been added to this treat!</p>
}
else
{
    <h4>This treat has these flavors:</h4>
    <ul>
        @foreach (FlavorTreat join in Model.JoinEntities)
        {
            <li>@join.Flavor.Name</li>
            @using (Html.BeginForm("DeleteJoin", "Treats"))
            {
                @Html.Hidden("joinId", @join.FlavorTreatId)
                @Html.Hidden("treatId", @Model.TreatId)
                <input type="submit" value="Remove flavor" />
            }
        }
    </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId })</p>
<p>@Html.ActionLink("Add a flavor", "AddFlavor", new { id = Model.TreatId })</p>
@using (Html.BeginForm("Delete", "Treats", new { id = Model.TreatId }))
{
    <input type="submit" value="Delete" />
}

Bakery/Views/Treats/Edit.cshtml
@model Bakery.Models.Treat

<h2>Edit</h2>

<h4>Edit @Model.Name</h4>

@using (Html.BeginForm())
{
    <div class="form-layout">
        @Html.HiddenFor(model => model.TreatId)

        @Html.LabelFor(model => model.Name)
        @Html.EditorFor(model => model.Name)

        @Html.LabelFor(model => model.Description)
        @Html.EditorFor(model => model.Description)

        <input class="form-button" type="submit" value="Save" />
    </div>
}

Bakery/Views/Treats/Index.cshtml
@using Bakery.Models;


<h2>Treats</h2>

@if (@Model.Count == 0)
{
    <h4>No treats have been added.</h4>
}

<ul>
    @foreach (Treat t in Model)
    {
        <li>@Html.ActionLink($"{t.Name}", "Details", new { id = t.TreatId })</li>
    }

</ul>

@Html.ActionLink("Add a new treat", "Create")