Bakery/Models/Flavor.cs
using System.ComponentModel.DataAnnotations;
namespace Bakery.Models;

public class Flavor
{
    public int FlavorId { get; set; }
    [Required]
    public string Name { get; set; }
    public ApplicationUser User { get; set; }
    public List<FlavorTreat> JoinEntities { get; }
}

Bakery/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using Bakery.Models;

namespace Bakery.Controllers;

public class FlavorsController : Controller
{
    private readonly BakeryContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, BakeryContext db)
    {
        _userManager = userManager;
        _db = db;
    }

    public ActionResult Index()
    {
        List<Flavor> model = _db.Flavors.ToList();
        return View(model);
    }

    [Authorize]
    public ActionResult Create()
    {
        return View();
    }

    [Authorize]
    [HttpPost]
    public async Task<ActionResult> Create(Flavor flav)
    {
        if (!ModelState.IsValid)
        {
            return View(flav);
        }
        else
        {
            string userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ApplicationUser currentUser = await _userManager.FindByIdAsync(userId);
            flav.User = currentUser;
            _db.Flavors.Add(flav);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

    public ActionResult Details(int id)
    {
        Flavor flav = _db.Flavors
            .Include(flav => flav.JoinEntities)
            .ThenInclude(join => join.Treat)
            .FirstOrDefault(flav => flav.FlavorId == id);
        return View(flav);
    }

    [Authorize]
    public ActionResult Edit(int id)
    {
        Flavor flav = _db.Flavors.FirstOrDefault(flav => flav.FlavorId == id);
        return View(flav);
    }

    [Authorize]
    [HttpPost]
    public ActionResult Edit(Flavor flav)
    {
        _db.Flavors.Update(flav);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = flav.FlavorId });
    }

    [Authorize]
    [HttpPost]
    public ActionResult Delete(int id)
    {
        Flavor flav = _db.Flavors.FirstOrDefault(flav => flav.FlavorId == id);
        _db.Flavors.Remove(flav);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    [Authorize]
    public ActionResult AddTreat(int id)
    {
        Flavor flav = _db.Flavors.FirstOrDefault(flav => flav.FlavorId == id);
        ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
        return View(flav);
    }
    [Authorize]
    [HttpPost]
    public ActionResult AddTreat(Flavor flav, int treatId)
    {
#nullable enable
        FlavorTreat? joinEntity = _db.FlavorTreats.FirstOrDefault(join => (join.TreatId == treatId && join.FlavorId == flav.FlavorId));
#nullable disable
        if (joinEntity == null && treatId != 0)
        {
            _db.FlavorTreats.Add(new FlavorTreat() { TreatId = treatId, FlavorId = flav.FlavorId });
            _db.SaveChanges();
        }
        return RedirectToAction("Details", new { id = flav.FlavorId });
    }

    [Authorize]
    [HttpPost]
    public ActionResult DeleteJoin(int joinId, int flavId)
    {
        FlavorTreat joinEntry = _db.FlavorTreats.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
        _db.FlavorTreats.Remove(joinEntry);
        _db.SaveChanges();
        return RedirectToAction("Details", new { id = flavId });
    }
}

Bakery/Views/Flavors/AddTreat.cshtml
@model Bakery.Models.Flavor


<h2>Add a tag</h2>

<h4>Add a treat to @Model.Name</h4>

@using (Html.BeginForm())
{
    <div class="form-layout">
        @Html.HiddenFor(model => model.FlavorId)

        @Html.Label("Select a treat")
        @Html.DropDownList("TreatId")

        <input class="form-button" type="submit" value="Save" />
    </div>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Bakery/Views/Flavors/Create.cshtml
@model Bakery.Models.Flavor

<h2>Add a new flavor</h2>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
    <div class=form-layout>
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)

        <input class="form-button" type="submit" value="Add flavor" />
    </div>
}

@Html.ActionLink("Show all flavors", "Index")

Bakery/Views/Flavors/Details.cshtml
@using Bakery.Models
@model Bakery.Models.Flavor


<h2>Flavor Info</h2>
<hr />
<h3>@Html.DisplayFor(model => model.Name)</h3>

@if (@Model.JoinEntities.Count == 0)
{
    <p>No treats come in this flavor!</p>
}
else
{
    <h4>These treats are @Model.Name:</h4>
    <ul>
        @foreach (FlavorTreat join in Model.JoinEntities)
        {
            <li>@join.Treat.Name</li>
            @using (Html.BeginForm("DeleteJoin", "Flavors"))
            {
                @Html.Hidden("joinId", @join.FlavorTreatId)
                @Html.Hidden("flavId", @Model.FlavorId)
                <input type="submit" value="Remove treat" />
            }
        }
    </ul>
}

<p>@Html.ActionLink("Back to list", "Index")</p>
<p>@Html.ActionLink("Edit Flavor", "Edit", new { id = Model.FlavorId })</p>
<p>@Html.ActionLink("Add a treat", "AddTreat", new { id = Model.FlavorId })</p>
@using (Html.BeginForm("Delete", "Flavors", new { id = Model.FlavorId }))
{
    <input type="submit" value="Delete" />
}

Bakery/Views/Flavors/Edit.cshtml
@model Bakery.Models.Flavor


<h2>Edit</h2>

<h4>Edit @Model.Name</h4>

@using (Html.BeginForm())
{
    <div class="form-layout">
        @Html.HiddenFor(model => model.FlavorId)

        @Html.LabelFor(model => model.Name)
        @Html.EditorFor(model => model.Name)

        <input class="form-button" type="submit" value="Save" />
    </div>
}

<p>@Html.ActionLink("Back to list", "Index")</p>

Bakery/Views/Flavors/Index.cshtml
@using Bakery.Models;


<h2>Flavors</h2>


@if (@Model.Count == 0)
{
    <h4>No flavors have been added.</h4>
}

<ul>
    @foreach (Flavor f in Model)
    {
        <li>@Html.ActionLink($"{f.Name}", "Details", new { id = f.FlavorId })</li>
    }
</ul>

@Html.ActionLink("Add a new flavor", "Create")